Repository OZ-Coding-School/oz_externship_fe_01_team4, pull requests merged in 2025-06, with the labels that each got.

#8 chore: 절대 경로 적용(#5)
  tsconfig.app.json
  vite.config.ts
Labels: chore

#14 feat: cn 유틸리티 도입(#13)
  package-lock.json
  package.json
  src/utils/cn.ts
  tsconfig.app.json
  vite.config.ts
Labels: feature

#24 feat: 아이콘 공통 컴포넌트 구현(#20)
  package.json
  src/components/Icon.tsx
  src/types/icon.ts
  src/vite-env.d.ts
  vite.config.ts
Labels: feature

#21 feat: 모달 구현(#1)
  index.html
  src/assets/icons/modal/close.svg
  src/components/Header.tsx
  src/components/Modal.tsx
  src/components/Portal.tsx
  src/constants/portalTargetId.ts
  src/constants/zIndexDefine.ts
  src/store/modalStore.ts
  tsconfig.app.json
  vite.config.ts
Labels: feature

#27 chore: 웹훅 커스텀 테스트(#26)
  .github/workflows/discord-notifications.yml
Labels: chore

#25 feat: 사이드바 공통 컴포넌트 구현(#7)
  package-lock.json
  src/assets/icons/profile.svg
  src/assets/icons/sidebar/community.svg
  src/assets/icons/sidebar/down.svg
  src/assets/icons/sidebar/qna.svg
  src/assets/icons/sidebar/test.svg
  src/assets/icons/sidebar/up.svg
  src/assets/icons/sidebar/user.svg
  src/components/Header.tsx
  src/components/Icon.tsx
  src/components/Layout.tsx
  src/components/Sidebar/SideBarMenu.tsx
  src/components/Sidebar/SideBarMenuItem.tsx
  src/constants/menuData.ts
  src/types/icon.ts
  src/types/index.ts
  src/types/menu.ts
Labels: feature

#35 chore: 웹훅 파일 등록(#34)
  .github/workflows/discord-notifications.yml
Labels: chore

#31 feat: 표(테이블) 공통 컴포넌트 구현(#16)
  src/components/dataTable/DataTable.tsx
  src/components/dataTable/Pagination.tsx
  src/components/dataTable/TableHeader.tsx
  src/components/dataTable/TableRow.tsx
  src/hooks/dataTable/usePagination.ts
  src/hooks/dataTable/useSelection.ts
  src/hooks/dataTable/useSort.ts
  src/types/table.ts
Labels: feature

#39 feat: 기본 폰트 설정(#36)
  src/App.css
  src/assets/fonts/PretendardVariable.woff2
Labels: feature

#46 fix: 표(테이블) 컴포넌트 타입 table.ts 파일 업데이트(#45)
  src/types/table.ts
Labels: fix

#44 feat: 팝업 구현(#33)
  src/App.css
  src/assets/icons/popup/deleteConfirm.svg
  src/assets/icons/popup/error.svg
  src/assets/icons/popup/success.svg
  src/components/Modal.tsx
  src/components/PopUp.tsx
  src/constants/modal.ts
  src/constants/popUp.ts
Labels: feature

#48 feat: 드롭다운 공통 컴포넌트 구현(#4)
  src/App.css
  src/assets/icons/input/arrow.svg
  src/assets/icons/input/check.svg
  src/components/common/Dropdown.tsx
Labels: feature

#54 feat: 인풋 컴포넌트 수정(#3)
  src/components/common/Input.tsx
Labels: feature

#57 feat: 드롭다운 공통 컴포넌트 수정(#4)
  src/components/common/Dropdown.tsx
  src/constants/zIndexDefine.ts
Labels: feature

#74 chore: build-test action 대상 브랜치에서 main 제거(#73)
  .github/workflows/build-test.yml
Labels: chore

#76 chore: 컴포넌트 정리 및 폴더 컨벤션 케밥케이스로 변경(#75)
  src/App.tsx
  src/components/Button.tsx
  src/components/Icon.tsx
  src/components/common/Button.tsx
  src/components/common/Icon.tsx
  src/components/common/Input.tsx
  src/components/common/Modal.tsx
  src/components/common/PopUp.tsx
  src/components/common/Portal.tsx
  src/components/common/Toast.tsx
  src/components/common/data-table/DataTable.tsx
  src/components/common/data-table/Pagination.tsx
  src/components/common/data-table/TableHeader.tsx
  src/components/common/data-table/TableRow.tsx
  src/components/layout/Header.tsx
  src/components/layout/Layout.tsx
  src/components/layout/sidebar/SideBarMenu.tsx
  src/components/layout/sidebar/SideBarMenuItem.tsx
  src/constants/button/button.ts
  src/constants/layout/sidebar/menuData.ts
  src/constants/modal/modal.ts
  src/constants/popup/popUp.ts
  src/constants/portal/portalTargetId.ts
  src/constants/toast/closeIconMap.ts
  src/hooks/data-table/usePagination.ts
  src/hooks/data-table/useSelection.ts
  src/hooks/data-table/useSort.ts
  src/hooks/toast/useToast.tsx
  src/types/table.ts
  tsconfig.app.json
  vite.config.ts
Labels: chore

#68 fix: rebase 중 미반영된 Button 코드 반영(#66)
  src/components/common/Button.tsx
  src/constants/button/button.ts
Labels: fix

#78 chore: develop 브랜치가 최신상태인지 확인하는 github action 코드 추가(#77)
  .github/workflows/pr-merge-check.yml
Labels: chore

#81 fix: input 컴포넌트 type 수정 (#80)
  src/components/common/Input.tsx
Labels: fix
