Repository OZ-Coding-School/oz_externship_fe_01_team4, pull requests merged in 2025-07, with the labels that each got.

#87 feat: 쪽지 시험 목록 조회 기능 구현(#64)
  package-lock.json
  src/components/common/Dropdown.tsx
  src/components/common/DropdownField.tsx
  src/components/common/Input.tsx
  src/components/common/SearchBar.tsx
  src/constants/button/button.ts
  src/pages/quizzes/Quizzes.tsx
Labels: feature

#102 feat: 배포내역 조회 기능 구현(#93)
  src/components/common/data-table/TableRow.tsx
  src/constants/button/button.ts
  src/constants/urls.ts
  src/pages/quizzes/Deployments.tsx
  src/types/deployments.ts
  src/types/table.ts
  src/utils/filterOption.ts
Labels: feature

#108 feat: 과목 목록 조회 (#106)
  src/components/common/data-table/DataTable.tsx
  src/components/common/data-table/TableRow.tsx
  src/pages/courses/Subjects.tsx
  src/types/subjects.ts
  src/types/table.ts
Labels: feature

#109 feat: 쪽지시험 생성 기능구현(#98)
  src/constants/urls.ts
  src/hooks/data-table/usePagination.ts
  src/pages/courses/Subjects.tsx
  src/pages/quizzes/Deployments.tsx
  src/pages/quizzes/Quizzes.tsx
  src/pages/quizzes/Submissions.tsx
  src/types/table.ts
Labels: feature

#111 feat: 과정목록 조회 페이지
  src/constants/urls.ts
  src/pages/courses/Courses.tsx
Labels: feature

#89 feat: 쪽지시험 배포 일정 등록 모달 구현(#61)
  package-lock.json
  package.json
  src/components/common/data-table/DataTable.tsx
  src/components/common/data-table/TableRow.tsx
  src/components/create-schedule/ScheduleFormFields.tsx
  src/components/create-schedule/ScheduleModal.tsx
  src/constants/create-schedule/api.ts
  src/constants/create-schedule/auth.ts
  src/constants/create-schedule/formFields.ts
  src/constants/create-schedule/index.ts
  src/constants/create-schedule/labels.ts
  src/constants/create-schedule/modal.ts
  src/constants/create-schedule/placeholders.ts
  src/constants/create-schedule/styles.ts
  src/constants/create-schedule/validation.ts
  src/hooks/create-schedule/useScheduleForm.ts
  src/lib/api/scheduleApi.ts
  src/pages/quizzes/Quizzes.tsx
  src/store/create-schedule/scheduleStore.ts
  src/types/createSchedule.ts
  src/types/table.ts
  src/utils/scheduleUtils.ts
Labels: feature

#116 feat: 로그인 후 엑세스 토큰 받아오는 기능(#112)
  package-lock.json
  package.json
  src/App.tsx
  src/api/axiosInstance.ts
  src/constants/button/button.ts
  src/constants/urls.ts
  src/hooks/useAuth.ts
  src/pages/Login.tsx
  src/pages/courses/Courses.tsx
  src/pages/courses/Subjects.tsx
  src/pages/quizzes/Deployments.tsx
  src/pages/quizzes/Quizzes.tsx
  src/types/user.ts
  src/utils/cookies.ts
  src/utils/navigation.ts
  tsconfig.app.json
  vite.config.ts
Labels: feature

#117 feat: 쪽지시험 상세 조회 모달 외형(#65)
  package-lock.json
  package.json
  src/App.css
  src/assets/icons/quizzes/detail-modal/checkIcon.svg
  src/components/common/SearchBar.tsx
  src/components/quizzes/detail-modal/DetailModal.tsx
  src/components/quizzes/detail-modal/components/AnswerCircle.tsx
  src/components/quizzes/detail-modal/components/QuizzesWrapper.tsx
  src/components/quizzes/detail-modal/components/SlideItem.tsx
  src/components/quizzes/detail-modal/components/questions/FillInBlank.tsx
  src/components/quizzes/detail-modal/components/questions/MultipleChoiceMulti.tsx
  src/components/quizzes/detail-modal/components/questions/MultipleChoiceSingle.tsx
  src/components/quizzes/detail-modal/components/questions/Ordering.tsx
  src/components/quizzes/detail-modal/components/questions/Ox.tsx
  src/components/quizzes/detail-modal/components/questions/ShortAnswer.tsx
  src/types/quizzes/quizTypes.ts
  src/utils/question/parseQuestionType.ts
Labels: feature

#122 feat: 과목 상세 조회 모달 구현(#115)
  src/components/common/FormRow.tsx
  src/components/common/data-table/DataTable.tsx
  src/components/common/data-table/TableRow.tsx
  src/components/subject/SubjectDetailModal.tsx
  src/pages/courses/Subjects.tsx
  src/types/subjects.ts
  src/utils/formatDate.ts
  src/utils/renderStatus.tsx
Labels: feature

#125 refactor: quizzes 페이지 코드 리팩토링(#124)
  src/components/quizzes/add-exam-modal/AddExamModal.tsx
  src/components/quizzes/course-filter-modal/CourseFilterModal.tsx
  src/pages/quizzes/Quizzes.tsx
Labels: feature

#129 feat: quizzes 페이지와 상세조회 모달 연결(#126)
  src/components/common/Button.tsx
  src/components/common/data-table/TableRow.tsx
  src/components/quizzes/detail-modal/DetailModal.tsx
  src/pages/quizzes/Quizzes.tsx
  src/types/quizzes/quizTypes.ts
Labels: feature

#130 feat: 과목 조회 페이지에 API 구조 리팩토링 및 React Query 적용(#128)
  src/App.tsx
  src/api/auth/authAPI.ts
  src/api/axiosInstance.ts
  src/api/instance/axiosInstance.ts
  src/api/instance/interceptors.ts
  src/api/instance/tokenHandler.ts
  src/api/instance/tokenQueue.ts
  src/api/subjects/subjectAPI.ts
  src/components/quizzes/add-exam-modal/AddExamModal.tsx
  src/components/subject/SubjectDetailModal.tsx
  src/hooks/queries/useSubjects.ts
  src/pages/courses/Courses.tsx
  src/pages/courses/Generations.tsx
  src/pages/courses/Subjects.tsx
  src/pages/quizzes/Deployments.tsx
  src/pages/quizzes/Quizzes.tsx
Labels: feature

#127 feat: 과정 상세조회 모달 구현(#114)
  src/assets/oz_round_logo.svg
  src/components/course/CourseDetailModal.tsx
  src/constants/urls.ts
  src/pages/courses/Courses.tsx
Labels: feature

#133 feat: 과목 등록 모달 구현 및 안정적인 API 에러 처리 개선(#123)
  src/api/instance/tokenHandler.ts
  src/api/subjects/subjectAPI.ts
  src/components/common/data-table/DataTable.tsx
  src/components/courses/add-courses-modal/AddCoursesModal.tsx
  src/components/quizzes/add-exam-modal/AddExamModal.tsx
  src/components/quizzes/course-filter-modal/CourseFilterModal.tsx
  src/components/subject/add-subject-modal/AddSubjectModal.tsx
  src/components/subject/detail-modal/SubjectDetailModal.tsx
  src/hooks/queries/useSubjects.ts
  src/pages/courses/Generations.tsx
  src/pages/courses/Subjects.tsx
  src/pages/quizzes/Quizzes.tsx
  src/utils/renderStatus.tsx
Labels: feature

#135 feat: 상세조회 모달과 문제등록 모달 연결(#120)
  src/api/quizzes/index.ts
  src/assets/icons/quizzes/detail-modal/addQuestion.svg
  src/assets/icons/quizzes/detail-modal/deleteQuestion.svg
  src/assets/icons/quizzes/detail-modal/editQuestion.svg
  src/assets/icons/quizzes/detail-modal/noImage.svg
  src/components/common/data-table/DataTable.tsx
  src/components/quizzes/add-exam-modal/AddExamModal.tsx
  src/components/quizzes/add-quiz-modal/AddQuizModal.tsx
  src/components/quizzes/add-quiz-modal/components/answer-register/Answer.tsx
  src/components/quizzes/add-quiz-modal/components/blank-answer-register/BlankAnswerRegister.tsx
  src/components/quizzes/add-quiz-modal/components/blank-answer-register/BlankQuestionOption.tsx
  src/components/quizzes/add-quiz-modal/pages/FillInTheBlanks.tsx
  src/components/quizzes/add-quiz-modal/pages/MultipleChoice.tsx
  src/components/quizzes/add-quiz-modal/pages/SortByOrder.tsx
  src/components/quizzes/add-quiz-modal/pages/SubjectiveShortAnswer.tsx
  src/components/quizzes/add-quiz-modal/pages/TrueOrFalse.tsx
  src/components/quizzes/detail-modal/DetailModal.tsx
  src/components/quizzes/detail-modal/components/NoQuestionSlideItem.tsx
  src/components/quizzes/detail-modal/components/QuizzesWrapper.tsx
  src/components/quizzes/detail-modal/components/SlideItem.tsx
  src/constants/button/button.ts
  src/pages/quizzes/Quizzes.tsx
  src/types/quizzes/quizFormTypes.ts
  src/types/quizzes/quizTypes.ts
  src/utils/navigation.ts
Labels: feature

#136 feat: 기수 및 기수등록 모달 , 과목 관리 페이지 기능 개선 (React Query 적용 및 필터링 최적화)(#110)
  src/api/courses/index.ts
  src/api/generations/index.ts
  src/api/subjects/index.ts
  src/components/common/data-table/DataTable.tsx
  src/components/common/data-table/TableRow.tsx
  src/components/generations/add-generation-modal/AddGenerationModal.tsx
  src/components/subject/add-subject-modal/AddSubjectModal.tsx
  src/constants/urls.ts
  src/hooks/queries/useCourses.ts
  src/hooks/queries/useGenerationDetail.ts
  src/hooks/queries/useGenerations.ts
  src/hooks/queries/useSubjects.ts
  src/pages/courses/Courses.tsx
  src/pages/courses/Generations.tsx
  src/pages/courses/Subjects.tsx
  src/types/courses.ts
  src/types/generations/generations.ts
Labels: feature

#138 chore: 모든 콘솔로그 코드 제거(#137)
  src/api/generations/index.ts
  src/api/instance/tokenHandler.ts
  src/components/courses/add-courses-modal/AddCoursesModal.tsx
  src/components/create-schedule/ScheduleModal.tsx
  src/components/generations/add-generation-modal/AddGenerationModal.tsx
  src/components/quizzes/add-exam-modal/AddExamModal.tsx
  src/components/quizzes/detail-modal/DetailModal.tsx
  src/components/subject/add-subject-modal/AddSubjectModal.tsx
  src/hooks/useAuth.ts
  src/pages/courses/Courses.tsx
  src/pages/courses/Subjects.tsx
  src/pages/quizzes/Deployments.tsx
  src/utils/navigation.ts
Labels: chore

#140 refactor: API 구조 개선(#139)
  src/api/generations/index.ts
  src/api/schedule/index.ts
  src/lib/api/scheduleApi.ts
  src/lib/index.ts
  src/pages/quizzes/Quizzes.tsx
  tsconfig.app.json
  vite.config.ts
Labels: refactor

#144 feat: 타이틀 수정, submitQuizData 최신화, 퀴즈페이지 버튼 수정(#143)
  index.html
  src/api/quizzes/index.ts
  src/components/quizzes/detail-modal/DetailModal.tsx
  src/constants/button/button.ts
  src/pages/quizzes/Quizzes.tsx
  src/types/quizzes/quizTypes.ts
Labels: feature

#149 fix: CORS 오류 해결(#148)
  vite.config.ts
Labels: fix

#151 feat: 과정 드롭다운 api 수정(#145)
  src/api/courses/index.ts
  src/api/generations/index.ts
  src/components/generations/add-generation-modal/AddGenerationModal.tsx
  src/components/subject/add-subject-modal/AddSubjectModal.tsx
  src/constants/urls.ts
  src/hooks/queries/useCoursesDropdown.ts
  src/pages/quizzes/Quizzes.tsx
  src/types/courses.ts
Labels: feature

#157 fix: 과정 상세 모달 페이지 안 열리는 오류 수정(#156)
  src/pages/courses/Courses.tsx
Labels: fix

#163 docs: README.md 작성(#162)
  README.md
Labels: docs

#161 release: v1.0.0 배포
  README.md
  index.html
  src/api/courses/index.ts
  src/api/deployments/index.ts
  src/api/generations/index.ts
  src/api/quizzes/index.ts
  src/api/submissions/index.ts
  src/components/common/PopUp.tsx
  src/components/common/data-table/TableRow.tsx
  src/components/generations/add-generation-modal/AddGenerationModal.tsx
  src/components/quizzes/detail-modal/DetailModal.tsx
  src/components/subject/add-subject-modal/AddSubjectModal.tsx
  src/constants/button/button.ts
  src/constants/urls.ts
  src/hooks/queries/useCoursesDropdown.ts
  src/hooks/queries/useDeployments.ts
  src/hooks/queries/useSubmissions.ts
  src/pages/courses/Courses.tsx
  src/pages/courses/Subjects.tsx
  src/pages/quizzes/Deployments.tsx
  src/pages/quizzes/Quizzes.tsx
  src/pages/quizzes/Submissions.tsx
  src/types/courses.ts
  src/types/deployments.ts
  src/types/quizzes/quizTypes.ts
  src/types/submission.ts
  vite.config.ts
Labels: release

#167 fix: 점수 제한 복구(#165)
  src/components/quizzes/detail-modal/DetailModal.tsx
Labels: fix

#171 fix: 쪽지시험 배포 일정 생성 api 엔드포인트 수정(#169)
  src/api/schedule/index.ts
  src/components/create-schedule/ScheduleModal.tsx
  src/constants/urls.ts
Labels: fix

#172 feat: 퀴즈 페이지에 토스트 추가, 화면전환 개선(#170)
  src/components/quizzes/detail-modal/DetailModal.tsx
  src/pages/quizzes/Quizzes.tsx
Labels: feature

#174 fix: 쪽지시험 배포 일정 생성 엔드포인트 수정(#173)
  src/constants/urls.ts
Labels: fix

#175 release: v1.0.1 배포
  README.md
  src/api/schedule/index.ts
  src/components/create-schedule/ScheduleModal.tsx
  src/components/quizzes/detail-modal/DetailModal.tsx
  src/constants/urls.ts
  src/pages/quizzes/Quizzes.tsx
Labels: release

#178 fix: 쪽지시험 페이지 버그 해결(#177)
  src/components/quizzes/detail-modal/DetailModal.tsx
  src/components/quizzes/detail-modal/components/questions/MultipleChoiceMulti.tsx
  src/components/quizzes/detail-modal/components/questions/MultipleChoiceSingle.tsx
  src/components/quizzes/detail-modal/components/questions/Ox.tsx
Labels: fix
